__title__ = 'feature engineering: one-hot'
__description__ = 'AI For Feature Engineering'
__version__ = '0.1.0'
__url__ = 'https://github.com/Yeahp/feature_engineering'
__author__ = 'eric p. qi'
__author_email__ = 'yeerxi@163.com'
__license__ = 'Free For Licence'
__copyright__ = 'Copyright 2019'